---
functional:
  - Требование 3
  - Требование 4
  - Требование 8
  - Требование 9
non-functional:
  - Требование 2
  - Требование 7
  - Требование 6
  - Требование 10
  - Требование 5
  - Требование 1
implicit:
  - Пользователь должен иметь возможность, при добавлении товара в корзину, выбирать количество товара
  - Меню категорий товаров с левой стороны
  - Изображения товаров
  - Отображение итоговой цены
